### ISSUE TITLE
Problem with model.save()

### ISSUE THREAD

**Issue by filiporestav** [featurestorebook/mlfs-book#20]
Hi, I have a problem with model.save() as in the ch03/3_air_quality_training_pipeline.ipynb notebook.

`aq_model.save(model_dir)`

I am constantly pending between these two errors:
```
RestAPIError: Metadata operation error: (url: https://c.app.hopsworks.ai/hopsworks-api/api/project/1177751/dataset/%2FProjects%2Fhoomiesv%2FModels%2Fair_quality_xgboost_model%2F1). Server response: 
HTTP code: 504, HTTP reason: Gateway Time-out, body: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?061f72ab-5a8f-451b-9ce2-2d5b9f913428) or open in a [text editor](command:workbench.action.openLargeOutput?061f72ab-5a8f-451b-9ce2-2d5b9f913428). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```

and

`ModelRegistryException: Model with name air_quality_xgboost_model and version 1 already exists`

Do you know what might be the issue? There is no model in the model registery on my Hopsworks UI.

**Comment by jimdowling** [comment]
This problem was due to underprovisioned cluster. The error message was due to a cluster underprovisioning issue.
It has been resolved.
