### ISSUE TITLE
Problem with aq_model.save(model_dir)

### ISSUE THREAD

**Issue by LudvigJohansson99** [featurestorebook/mlfs-book#21]
At the end of notebook3 on the line: aq_model.save(model_dir) i get the following error:
RestAPIError: Metadata operation error: (url: https://c.app.hopsworks.ai/hopsworks-api/api/project/1163418/dataset/upload/%2FProjects%2FLab1Scaleable%2FModels%2Fair_quality_xgboost_model%2F7%5Cimages). Server response: 
HTTP code: 400, HTTP reason: Invalid URI, body: b''
The error can be solved by removing the image folder from air_quality_model but then the evaluation images do not end up on the hopsworks page. How should this be solved?

**Comment by jimdowling** [comment]
This problem was due to a bug for windows clients.
Please upgrade the hopsworks client for a fix.
